language: android
sudo: required
jdk: oraclejdk8

# Include branches
branches:
  only:
    - master
    - v5
    - v6
    - travis-setup

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

env:
  global:
    - ANDROID_BUILD_API=28
    - ANDROID_BUILD_TOOLS=28.0.3
    - ANDROID_EMULATOR_API=24
    - ADB_INSTALL_TIMEOUT=5 # minutes
    - ANDROID_ABI=default/armeabi-v7a
    - secure: Qs0T6M0fWNfrEcfmA6i97wK2kwQaQE8iqIvix5C9iho5XBZAadA/5StFpPXBVEvBGvbPr/mDuPoj69fY+q3nf/rzllGKZb4gAub1uR4gyvaBkN4RA0kgiAGktiTSn1OJj49Vq+ENITp6hWf+upnBmymaryWMpugX+Jbp2wzY3vGd+hf9aAWwVrSu2163awa3a55WcTqhtYcaTb9wz+nu7EjBb6TVTvdk8xGPPBCBk3NvQru5MSMTnn13kDWT1/KZMXZE7gPm1/im4ahjo9jksjQOpp+lGW1jJrwlKgBYjZKI0GJZcno2EsE3S4eTFBBbInJmXejXMvsH9LK7RYHEDOHfCBGKmcO0eqOGv5US+ehPUHMZWMHFiPYjs/q8IxGixvn9n7eLQ2y03okC8IlRltzOIpkv2XzR22iWXX4jL7ARE8vfKU32XuLvbgC/UHCxmAZVeAgftTDC3PxCYnw7kCQLMNo+mZMFxqh1eMViLXrStWWIrvMbgaCkBF2hgCRmAAMpjPG0Wz90ISZlfCthwJ5dG4jJxifHScw3gG2qlqCtRiwzoDoTKz3XuTi7GwWPZCtkxPr3hon/PBXf7wT4gWzya5cYw2sNgdGWQ/9af6O82bSh6wTiDFSRSmwaIyHWes8548EPJHMRT/o5hF+0RNNofhgxBG0J5yob5O84tzM=
    - secure: FjBWuxUikJi7Cizy9FQtyge68JWstJwzLfG41FrQUJMpRLesOhX1PYwpd1p0qSzGDAGsJrCYNCTuMlgU9zkVj+RrC57gZjR+pC7uivXxZVyVaRb0ZKwaMMrpI3xCl9LMsNw+VgiE4mOOZlsDZx52kqN+tg7uJyGji0xiWCSvh1l3O8FTyhC7Ag/b2aZfTTFN169F/W3palRBJcXZs7k59DfLzsqC8IX+FeCpY0ijnt3YnVjGCjk8x3Y7wB+QibHc++K8mx0DTLcmZoVL4J1w4L6du65umP7s6bkEnZjF8d9UV65lTTEK00YIyYqqiYazJpA284qBnvcEUO9t2QuQJNDChU2KFIGOBBDvRj11/0jIgJE5OIyok6KXEOXaWxaa066myy6a5KC8m23cFwxuH191x047Fr2XsCGPtRMtdvwXJUv25EwrMS/yKzCBwZVJ73oMIBEvEY8bL2suOpoa9X6nSMs6zqDdAUyl4KYu2Ze2sRW431RGQYYUjsSca5wuaHvg5/oL/yapQAIYGe5AI5B3PBRfbDUD+oxc1nb6LuFH+V/NCterCQN9udyTfxzamdy3HazkJN9N7X5OOq2aXXimroNKDO5A2s2r3mWblrkYej6ekWEYy5lVmecChag8Y/ThjoXKTF+w9ACyIgvCE/Z2C3CEmWkiImANTxuZw90=
    - secure: WN2KJh2AlllXS7ZyHZWELGNbzckDAwWlL10E25U1SL1R2t9csT8b+iqgCdiIa42eVYhqfdSijqBYEysULOeJQzeBaeU0WSi8rxt6pISrgpAJHQN7TnWzurcz1NwmWWTooJpxnERRCripjAeIbpf9hFJgnybAFv+ujHBkr9IIPYKQgpv1xT1uHZI7/jZTXXsQIE6B8NrmCSiAK1wLdfwd/Tv5wYq3CGdwG10/9+WGPvsfZH6v9C/JzBvmnHLWBkEbEOi1jE50fPsMKWMZ7Caa+RWVbf83ydtX7lBiFcjvDrsLVcl9deISlInFV4I7FITh0+nHjgRUlOfZxDpika6n5XK1Q4FCHkT96LJl9Tmb8WbqtXA3w84yhSM71yTVMYpcNKkMnh9TaObYbLgYzcv0N1XLLXqRH5xRyI7Jtf1PLzyNKTKX+tHPY9YTBjNW5vv2PZGV+04Hc9uvHKAtFcQWlVnaOrBQ2PLVwifIzAS3XT6Eh1mbBwaS3mL7Es8FrGCdC2POsGN3AdXrhNfy+QqB1YDu6YvX/pNSZ98ZIT4ksTRgdD41Jz199/kWkzGV7ib+NkKEGiatnLXz9fei58J4fv4t95o4bPloCpJMKNWW3fYmUdy4NgLscU2q7QT1a4CqJByPRvuJjg9t+tqQHFsU9tm85Ub9KuaQzuA/Tl9WUxU=
    - secure: j/7qEdTrgn7S88VJJl5Ko0h9nSH5tNc18cnkIIRbeE4ZtkqWGiB4viSI5EF66cO47cAdxhP13iNqYkGx+ukDeTD04HB5n7s/XnFZbNY73GIIfsyjqNfssXD4YqV/UmDnqdF5LkO7Fv2jJbFSMt4u6d77coiMIArgqCvWo1HcY4cjMiqCpMVb8xznwSBDTw6wUCXElBo4aEEpmWClwStJwv2F37+407cP2AtXJZvtKyjjMnpbgA2Q9HIZfDQuylLI695bxYba5dQLrbxpsTalU+Ij/167co2csXaQqfZSFAXxZTLIuwm3BZJ3+mKB/csz6UnKCeDm7q1inaGj8PhMoFc+9I3c2yVWtNu2mp1m+tskCMZVibAJrQt3gUjiQSMOsNlPrlFhZ3dQ8fjO4//QxkTdEb6UWQ6HN1uRqO/s1FDR2lmBMbnLFqK9N7qFJ2ofHrWBMp1OJF6owscF2FWbc2Iwtlhxc8EtX/OyhgxMtGuRpSSxMlNwH4sNORzQUCptndtcDQfQpvgmfK+M/upWjRSkgDNatFa3B9cE7vMvL5cwDOP5BOqsDIvUn+MU0rGwvjfmPCSR1Dd0I5TNDLkUXrmsIY9wNRNodIGXuv3CHLYNVLVNpI4B5KyVO60j4cEcrAQ6o9KOpDErJ5PuADCKKU73ATAbAx33ACbY3b1FNSo=
    - secure: MxN3JJwxPaAj3JZwiWOsVq77JpgDZ52IzF+hxf0ClwIYAbux9uZ2BIrCWg/xRBjgduMM4UYRRZxippqobc9ENIi1yi/ZKz/aTZNRxXtnLJeN89HpZJtB7vd5bOkZyRdi6IJDJcbbiAVb8qClrNim0exFc4gMqZIHR18BtAOqxJ5VFXZcXgjelT87y+kAbpgQdBBZhjEeMdBDM2xr2GTip+LuOT5A0rTF/msD2pr3jykp1WbS1T694Gr+jnFZeBwxYKymFqd27D+2rMnEJ8rB/YJSpm+13oc5tvurlChCi7ngoSkpjglW48nFSO5x3dhvl9/VZBI6339zEKiiTK0ZJQGwWMLJ6sGp64cxnvOfe477CJQA2AHIavcaIrmNGk1pDSCieLya6sNjHGY4jtshfmWaG71mGBq63N6MjuWPjosAka/2I3/zSC8RfLCkzH4nYM7B4GzikM10xcD7SZ0o9nIfCmn9EVrK0BRJEBv/gEEWKvPN+dVmqgOjGTn3snhE2DQyATfVh7BGSFqRtPziNMRhdjifYUUYzjKDboTahUSm99jmILF1TPJDCwx7xn0D5U6HA42NREXPF43SEEoUkeo5592Rb7KD4Nn6xQjLvQ8kJV9McinT2hKmYcQgupdHljyT6Zk0J5N3H4ft85vE4/TTuqHMO4yNW+G+RmkVQ9M=
    - secure: lvHv9kgv3cnxpdrxbgNKyYV7ISQA0oYvjGvL3nfpcZ16+8tbAj3U+bd46rpcNq70RZkNZpEfli9N1R7ZamBMKXbDaHWwEAW+pFeldT0jhoie5DMmzQp5c8Sjn7jT0Iu91/qFHEQZaxcEBNZCo2W2UUSThfRHBk1tgbX1pr5zPmkG6/6cN7Bp2qMlfAcr9fXi0HEAO4xyAtQnZXf9zYNkcQYn2VeRqZC39UQsb0REXxD90/b0oe2SAnb4211Mgw9SadyvW1LZonqBvLmhp+BG6uUAYWj/ZyRhkg9thMY7sFEsPwf3VfaeR2aY7dTVJyJKY4KWAk3fJFio3cAaiYv/opFMrbp0TbYZFZd8qRVqHWymUd/NXTzgBg2URrGzNGwJVH+WidA2HcltuIBkCy5d6Og8AHKijhVsM0aKIiHnc9JhvKOyvj13Q1XKgv7FyiSG2Iy6Ws25O0VH7f/JAr0DucM0s930cTERBPUaFW7dEfgD1tfNyWeRZSMNjaS24z2WpIdNZKXsYsgDj6mgtq3rToZqTDNhyz1gHAkSp+dnWO0ZwS1VR985T7A1Gu1n9f0HQWT6FcPUC3NQQKRUSqF0lJVn0dpdKI0kmwTeNKQduXeVLr7QLyrENixz6ASbJqBoMvF0oAcdjhwqSKHRmfrY+jmQfAyBrDJbmE1GJe7r7j4=

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # to install Android SDK tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_BUILD_API
    - android-$ANDROID_EMULATOR_API
    - extra-android-m2repository # for design library
    - extra-google-m2repository
    - extra-google-google_play_services
    - addon-google_apis-google-28 # google play services
    - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_BUILD_API
    - sys-img-armeabi-v7a-android-$ANDROID_EMULATOR_API

  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - yes | sdkmanager "platforms;android-28"
  - mkdir -p "$ANDROID_HOME/licenses"
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - chmod +x gradlew
  - ./gradlew dependencies || true

before_script:
  - android list targets
  - android list sdk --extended --no-ui --all
  - echo "y" | android update sdk -a --no-ui --filter sys-img-armeabi-v7a-android-$ANDROID_EMULATOR_API,sys-img-x86_64-android-$ANDROID_EMULATOR_API
  - echo no | android create avd --force -n test -t android-$ANDROID_EMULATOR_API --abi $ANDROID_ABI
  - QEMU_AUDIO_DRV=none emulator -avd test -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - "./gradlew :crypto:clean :crypto:test"
  - "./gradlew :sdk:clean :sdk:test"
  - "./gradlew :crypto-android:clean :crypto-android:connectedCheck -PdisablePreDex --stacktrace"
  - "./gradlew :android-utils:clean :android-utils:connectedCheck -PdisablePreDex --stacktrace"
