/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.virgilsecurity.crypto;

public class VirgilPBE extends VirgilAsn1Compatible implements java.lang.AutoCloseable {
  private transient long swigCPtr;

  protected VirgilPBE(long cPtr, boolean cMemoryOwn) {
    super(virgil_crypto_javaJNI.VirgilPBE_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VirgilPBE obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        virgil_crypto_javaJNI.delete_VirgilPBE(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  @Override
  public void close() {
    delete();
  }

  public VirgilPBE() {
    this(virgil_crypto_javaJNI.new_VirgilPBE__SWIG_0(), true);
  }

  public VirgilPBE(VirgilPBE.Algorithm alg, byte[] salt, long iterationCount) {
    this(virgil_crypto_javaJNI.new_VirgilPBE__SWIG_1(alg.swigValue(), salt, iterationCount), true);
  }

  public VirgilPBE(VirgilPBE.Algorithm alg, byte[] salt) {
    this(virgil_crypto_javaJNI.new_VirgilPBE__SWIG_2(alg.swigValue(), salt), true);
  }

  public byte[] encrypt(byte[] data, byte[] pwd) {
    return virgil_crypto_javaJNI.VirgilPBE_encrypt(swigCPtr, this, data, pwd);
  }

  public byte[] decrypt(byte[] data, byte[] pwd) {
    return virgil_crypto_javaJNI.VirgilPBE_decrypt(swigCPtr, this, data, pwd);
  }

  public final static class Algorithm {
    public final static VirgilPBE.Algorithm PKCS5 = new VirgilPBE.Algorithm("PKCS5");
    public final static VirgilPBE.Algorithm PKCS12 = new VirgilPBE.Algorithm("PKCS12");

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static Algorithm swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + Algorithm.class + " with value " + swigValue);
    }

    private Algorithm(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private Algorithm(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private Algorithm(String swigName, Algorithm swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static Algorithm[] swigValues = { PKCS5, PKCS12 };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

  public final static long kIterationCountMin = virgil_crypto_javaJNI.VirgilPBE_kIterationCountMin_get();
}
