/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.virgilsecurity.crypto;

public class VirgilAsn1Reader implements java.lang.AutoCloseable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VirgilAsn1Reader(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VirgilAsn1Reader obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        virgil_crypto_javaJNI.delete_VirgilAsn1Reader(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  public void close() {
    delete();
  }

  public VirgilAsn1Reader() {
    this(virgil_crypto_javaJNI.new_VirgilAsn1Reader__SWIG_0(), true);
  }

  public VirgilAsn1Reader(byte[] data) {
    this(virgil_crypto_javaJNI.new_VirgilAsn1Reader__SWIG_1(data), true);
  }

  public void reset(byte[] data) {
    virgil_crypto_javaJNI.VirgilAsn1Reader_reset(swigCPtr, this, data);
  }

  public int readInteger() {
    return virgil_crypto_javaJNI.VirgilAsn1Reader_readInteger(swigCPtr, this);
  }

  public boolean readBool() {
    return virgil_crypto_javaJNI.VirgilAsn1Reader_readBool(swigCPtr, this);
  }

  public void readNull() {
    virgil_crypto_javaJNI.VirgilAsn1Reader_readNull(swigCPtr, this);
  }

  public byte[] readOctetString() {
    return virgil_crypto_javaJNI.VirgilAsn1Reader_readOctetString(swigCPtr, this);
  }

  public byte[] readUTF8String() {
    return virgil_crypto_javaJNI.VirgilAsn1Reader_readUTF8String(swigCPtr, this);
  }

  public byte[] readData() {
    return virgil_crypto_javaJNI.VirgilAsn1Reader_readData(swigCPtr, this);
  }

  public long readContextTag(short tag) {
    return virgil_crypto_javaJNI.VirgilAsn1Reader_readContextTag(swigCPtr, this, tag);
  }

  public String readOID() {
    return virgil_crypto_javaJNI.VirgilAsn1Reader_readOID(swigCPtr, this);
  }

  public long readSequence() {
    return virgil_crypto_javaJNI.VirgilAsn1Reader_readSequence(swigCPtr, this);
  }

  public long readSet() {
    return virgil_crypto_javaJNI.VirgilAsn1Reader_readSet(swigCPtr, this);
  }

}
