/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.virgilsecurity.crypto;

public class VirgilCMSPasswordRecipient extends VirgilAsn1Compatible implements java.lang.AutoCloseable {
  private transient long swigCPtr;

  protected VirgilCMSPasswordRecipient(long cPtr, boolean cMemoryOwn) {
    super(virgil_crypto_javaJNI.VirgilCMSPasswordRecipient_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VirgilCMSPasswordRecipient obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        virgil_crypto_javaJNI.delete_VirgilCMSPasswordRecipient(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  @Override
  public void close() {
    delete();
  }

  public void setKeyDerivationAlgorithm(byte[] value) {
    virgil_crypto_javaJNI.VirgilCMSPasswordRecipient_keyDerivationAlgorithm_set(swigCPtr, this, value);
  }

  public byte[] getKeyDerivationAlgorithm() {
    return virgil_crypto_javaJNI.VirgilCMSPasswordRecipient_keyDerivationAlgorithm_get(swigCPtr, this);
  }

  public void setKeyEncryptionAlgorithm(byte[] value) {
    virgil_crypto_javaJNI.VirgilCMSPasswordRecipient_keyEncryptionAlgorithm_set(swigCPtr, this, value);
  }

  public byte[] getKeyEncryptionAlgorithm() {
    return virgil_crypto_javaJNI.VirgilCMSPasswordRecipient_keyEncryptionAlgorithm_get(swigCPtr, this);
  }

  public void setEncryptedKey(byte[] value) {
    virgil_crypto_javaJNI.VirgilCMSPasswordRecipient_encryptedKey_set(swigCPtr, this, value);
  }

  public byte[] getEncryptedKey() {
    return virgil_crypto_javaJNI.VirgilCMSPasswordRecipient_encryptedKey_get(swigCPtr, this);
  }

  public VirgilCMSPasswordRecipient() {
    this(virgil_crypto_javaJNI.new_VirgilCMSPasswordRecipient__SWIG_0(), true);
  }

  public VirgilCMSPasswordRecipient(VirgilCMSPasswordRecipient other) {
    this(virgil_crypto_javaJNI.new_VirgilCMSPasswordRecipient__SWIG_1(VirgilCMSPasswordRecipient.getCPtr(other), other), true);
  }

}
