/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.virgilsecurity.crypto;

public interface virgil_crypto_javaConstants {
  public final static int VIRGIL_CRYPTO_FEATURE_LOW_LEVEL_WRAP = virgil_crypto_javaJNI.VIRGIL_CRYPTO_FEATURE_LOW_LEVEL_WRAP_get();
}
