/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.virgilsecurity.crypto;

public class VirgilCMSContentInfo extends VirgilAsn1Compatible implements java.lang.AutoCloseable {
  private transient long swigCPtr;

  protected VirgilCMSContentInfo(long cPtr, boolean cMemoryOwn) {
    super(virgil_crypto_javaJNI.VirgilCMSContentInfo_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VirgilCMSContentInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        virgil_crypto_javaJNI.delete_VirgilCMSContentInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  @Override
  public void close() {
    delete();
  }

  public void setCmsContent(VirgilCMSContent value) {
    virgil_crypto_javaJNI.VirgilCMSContentInfo_cmsContent_set(swigCPtr, this, VirgilCMSContent.getCPtr(value), value);
  }

  public VirgilCMSContent getCmsContent() {
    long cPtr = virgil_crypto_javaJNI.VirgilCMSContentInfo_cmsContent_get(swigCPtr, this);
    return (cPtr == 0) ? null : new VirgilCMSContent(cPtr, false);
  }

  public void setCustomParams(VirgilCustomParams value) {
    virgil_crypto_javaJNI.VirgilCMSContentInfo_customParams_set(swigCPtr, this, VirgilCustomParams.getCPtr(value), value);
  }

  public VirgilCustomParams getCustomParams() {
    long cPtr = virgil_crypto_javaJNI.VirgilCMSContentInfo_customParams_get(swigCPtr, this);
    return (cPtr == 0) ? null : new VirgilCustomParams(cPtr, false);
  }

  public static long defineSize(byte[] data) {
    return virgil_crypto_javaJNI.VirgilCMSContentInfo_defineSize(data);
  }

  public VirgilCMSContentInfo() {
    this(virgil_crypto_javaJNI.new_VirgilCMSContentInfo__SWIG_0(), true);
  }

  public VirgilCMSContentInfo(VirgilCMSContentInfo other) {
    this(virgil_crypto_javaJNI.new_VirgilCMSContentInfo__SWIG_1(VirgilCMSContentInfo.getCPtr(other), other), true);
  }

}
