/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.virgilsecurity.crypto;

public class VirgilSigner extends VirgilSignerBase implements java.lang.AutoCloseable {
  private transient long swigCPtr;

  protected VirgilSigner(long cPtr, boolean cMemoryOwn) {
    super(virgil_crypto_javaJNI.VirgilSigner_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VirgilSigner obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        virgil_crypto_javaJNI.delete_VirgilSigner(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  @Override
  public void close() {
    delete();
  }

  public VirgilSigner(VirgilHash.Algorithm hashAlgorithm) {
    this(virgil_crypto_javaJNI.new_VirgilSigner__SWIG_0(hashAlgorithm.swigValue()), true);
  }

  public VirgilSigner() {
    this(virgil_crypto_javaJNI.new_VirgilSigner__SWIG_1(), true);
  }

  public byte[] sign(byte[] data, byte[] privateKey, byte[] privateKeyPassword) {
    return virgil_crypto_javaJNI.VirgilSigner_sign__SWIG_0(swigCPtr, this, data, privateKey, privateKeyPassword);
  }

  public byte[] sign(byte[] data, byte[] privateKey) {
    return virgil_crypto_javaJNI.VirgilSigner_sign__SWIG_1(swigCPtr, this, data, privateKey);
  }

  public boolean verify(byte[] data, byte[] sign, byte[] publicKey) {
    return virgil_crypto_javaJNI.VirgilSigner_verify(swigCPtr, this, data, sign, publicKey);
  }

}
