/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.virgilsecurity.crypto;

public class VirgilPFSSession implements java.lang.AutoCloseable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VirgilPFSSession(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VirgilPFSSession obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        virgil_crypto_javaJNI.delete_VirgilPFSSession(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  public void close() {
    delete();
  }

  public VirgilPFSSession() {
    this(virgil_crypto_javaJNI.new_VirgilPFSSession__SWIG_0(), true);
  }

  public VirgilPFSSession(byte[] identifier, byte[] encryptionSecretKey, byte[] decryptionSecretKey, byte[] additionalData) {
    this(virgil_crypto_javaJNI.new_VirgilPFSSession__SWIG_1(identifier, encryptionSecretKey, decryptionSecretKey, additionalData), true);
  }

  public boolean isEmpty() {
    return virgil_crypto_javaJNI.VirgilPFSSession_isEmpty(swigCPtr, this);
  }

  public byte[] getIdentifier() {
    return virgil_crypto_javaJNI.VirgilPFSSession_getIdentifier(swigCPtr, this);
  }

  public byte[] getEncryptionSecretKey() {
    return virgil_crypto_javaJNI.VirgilPFSSession_getEncryptionSecretKey(swigCPtr, this);
  }

  public byte[] getDecryptionSecretKey() {
    return virgil_crypto_javaJNI.VirgilPFSSession_getDecryptionSecretKey(swigCPtr, this);
  }

  public byte[] getAdditionalData() {
    return virgil_crypto_javaJNI.VirgilPFSSession_getAdditionalData(swigCPtr, this);
  }

}
