/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.virgilsecurity.crypto;

public class VirgilStreamSigner extends VirgilSignerBase implements java.lang.AutoCloseable {
  private transient long swigCPtr;

  protected VirgilStreamSigner(long cPtr, boolean cMemoryOwn) {
    super(virgil_crypto_javaJNI.VirgilStreamSigner_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VirgilStreamSigner obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        virgil_crypto_javaJNI.delete_VirgilStreamSigner(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  @Override
  public void close() {
    delete();
  }

  public VirgilStreamSigner(VirgilHash.Algorithm hashAlgorithm) {
    this(virgil_crypto_javaJNI.new_VirgilStreamSigner__SWIG_0(hashAlgorithm.swigValue()), true);
  }

  public VirgilStreamSigner() {
    this(virgil_crypto_javaJNI.new_VirgilStreamSigner__SWIG_1(), true);
  }

  public byte[] sign(VirgilDataSource source, byte[] privateKey, byte[] privateKeyPassword) {
    return virgil_crypto_javaJNI.VirgilStreamSigner_sign__SWIG_0(swigCPtr, this, VirgilDataSource.getCPtr(source), source, privateKey, privateKeyPassword);
  }

  public byte[] sign(VirgilDataSource source, byte[] privateKey) {
    return virgil_crypto_javaJNI.VirgilStreamSigner_sign__SWIG_1(swigCPtr, this, VirgilDataSource.getCPtr(source), source, privateKey);
  }

  public boolean verify(VirgilDataSource source, byte[] sign, byte[] publicKey) {
    return virgil_crypto_javaJNI.VirgilStreamSigner_verify(swigCPtr, this, VirgilDataSource.getCPtr(source), source, sign, publicKey);
  }

}
