/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.virgilsecurity.crypto;

public class VirgilPFS implements java.lang.AutoCloseable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VirgilPFS(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VirgilPFS obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        virgil_crypto_javaJNI.delete_VirgilPFS(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  public void close() {
    delete();
  }

  public VirgilPFS() {
    this(virgil_crypto_javaJNI.new_VirgilPFS(), true);
  }

  public VirgilPFSSession startInitiatorSession(VirgilPFSInitiatorPrivateInfo initiatorPrivateInfo, VirgilPFSResponderPublicInfo responderPublicInfo, byte[] additionalData) {
    return new VirgilPFSSession(virgil_crypto_javaJNI.VirgilPFS_startInitiatorSession__SWIG_0(swigCPtr, this, VirgilPFSInitiatorPrivateInfo.getCPtr(initiatorPrivateInfo), initiatorPrivateInfo, VirgilPFSResponderPublicInfo.getCPtr(responderPublicInfo), responderPublicInfo, additionalData), true);
  }

  public VirgilPFSSession startInitiatorSession(VirgilPFSInitiatorPrivateInfo initiatorPrivateInfo, VirgilPFSResponderPublicInfo responderPublicInfo) {
    return new VirgilPFSSession(virgil_crypto_javaJNI.VirgilPFS_startInitiatorSession__SWIG_1(swigCPtr, this, VirgilPFSInitiatorPrivateInfo.getCPtr(initiatorPrivateInfo), initiatorPrivateInfo, VirgilPFSResponderPublicInfo.getCPtr(responderPublicInfo), responderPublicInfo), true);
  }

  public VirgilPFSSession startResponderSession(VirgilPFSResponderPrivateInfo responderPrivateInfo, VirgilPFSInitiatorPublicInfo initiatorPublicInfo, byte[] additionalData) {
    return new VirgilPFSSession(virgil_crypto_javaJNI.VirgilPFS_startResponderSession__SWIG_0(swigCPtr, this, VirgilPFSResponderPrivateInfo.getCPtr(responderPrivateInfo), responderPrivateInfo, VirgilPFSInitiatorPublicInfo.getCPtr(initiatorPublicInfo), initiatorPublicInfo, additionalData), true);
  }

  public VirgilPFSSession startResponderSession(VirgilPFSResponderPrivateInfo responderPrivateInfo, VirgilPFSInitiatorPublicInfo initiatorPublicInfo) {
    return new VirgilPFSSession(virgil_crypto_javaJNI.VirgilPFS_startResponderSession__SWIG_1(swigCPtr, this, VirgilPFSResponderPrivateInfo.getCPtr(responderPrivateInfo), responderPrivateInfo, VirgilPFSInitiatorPublicInfo.getCPtr(initiatorPublicInfo), initiatorPublicInfo), true);
  }

  public VirgilPFSEncryptedMessage encrypt(byte[] data) {
    return new VirgilPFSEncryptedMessage(virgil_crypto_javaJNI.VirgilPFS_encrypt(swigCPtr, this, data), true);
  }

  public byte[] decrypt(VirgilPFSEncryptedMessage encryptedMessage) {
    return virgil_crypto_javaJNI.VirgilPFS_decrypt(swigCPtr, this, VirgilPFSEncryptedMessage.getCPtr(encryptedMessage), encryptedMessage);
  }

  public VirgilPFSSession getSession() {
    return new VirgilPFSSession(virgil_crypto_javaJNI.VirgilPFS_getSession(swigCPtr, this), true);
  }

  public void setSession(VirgilPFSSession session) {
    virgil_crypto_javaJNI.VirgilPFS_setSession(swigCPtr, this, VirgilPFSSession.getCPtr(session), session);
  }

}
