/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.virgilsecurity.crypto;

public class VirgilSignerBase implements java.lang.AutoCloseable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VirgilSignerBase(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VirgilSignerBase obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        virgil_crypto_javaJNI.delete_VirgilSignerBase(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  public void close() {
    delete();
  }

  public VirgilSignerBase(VirgilHash.Algorithm hashAlgorithm) {
    this(virgil_crypto_javaJNI.new_VirgilSignerBase__SWIG_0(hashAlgorithm.swigValue()), true);
  }

  public VirgilSignerBase() {
    this(virgil_crypto_javaJNI.new_VirgilSignerBase__SWIG_1(), true);
  }

  public VirgilHash.Algorithm getHashAlgorithm() {
    return VirgilHash.Algorithm.swigToEnum(virgil_crypto_javaJNI.VirgilSignerBase_getHashAlgorithm(swigCPtr, this));
  }

  public byte[] signHash(byte[] digest, byte[] privateKey, byte[] privateKeyPassword) {
    return virgil_crypto_javaJNI.VirgilSignerBase_signHash__SWIG_0(swigCPtr, this, digest, privateKey, privateKeyPassword);
  }

  public byte[] signHash(byte[] digest, byte[] privateKey) {
    return virgil_crypto_javaJNI.VirgilSignerBase_signHash__SWIG_1(swigCPtr, this, digest, privateKey);
  }

  public boolean verifyHash(byte[] digest, byte[] signature, byte[] publicKey) {
    return virgil_crypto_javaJNI.VirgilSignerBase_verifyHash(swigCPtr, this, digest, signature, publicKey);
  }

}
