/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.virgilsecurity.crypto;

public class VirgilCMSKeyTransRecipient extends VirgilAsn1Compatible implements java.lang.AutoCloseable {
  private transient long swigCPtr;

  protected VirgilCMSKeyTransRecipient(long cPtr, boolean cMemoryOwn) {
    super(virgil_crypto_javaJNI.VirgilCMSKeyTransRecipient_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VirgilCMSKeyTransRecipient obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        virgil_crypto_javaJNI.delete_VirgilCMSKeyTransRecipient(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  @Override
  public void close() {
    delete();
  }

  public void setRecipientIdentifier(byte[] value) {
    virgil_crypto_javaJNI.VirgilCMSKeyTransRecipient_recipientIdentifier_set(swigCPtr, this, value);
  }

  public byte[] getRecipientIdentifier() {
    return virgil_crypto_javaJNI.VirgilCMSKeyTransRecipient_recipientIdentifier_get(swigCPtr, this);
  }

  public void setKeyEncryptionAlgorithm(byte[] value) {
    virgil_crypto_javaJNI.VirgilCMSKeyTransRecipient_keyEncryptionAlgorithm_set(swigCPtr, this, value);
  }

  public byte[] getKeyEncryptionAlgorithm() {
    return virgil_crypto_javaJNI.VirgilCMSKeyTransRecipient_keyEncryptionAlgorithm_get(swigCPtr, this);
  }

  public void setEncryptedKey(byte[] value) {
    virgil_crypto_javaJNI.VirgilCMSKeyTransRecipient_encryptedKey_set(swigCPtr, this, value);
  }

  public byte[] getEncryptedKey() {
    return virgil_crypto_javaJNI.VirgilCMSKeyTransRecipient_encryptedKey_get(swigCPtr, this);
  }

  public VirgilCMSKeyTransRecipient() {
    this(virgil_crypto_javaJNI.new_VirgilCMSKeyTransRecipient__SWIG_0(), true);
  }

  public VirgilCMSKeyTransRecipient(VirgilCMSKeyTransRecipient other) {
    this(virgil_crypto_javaJNI.new_VirgilCMSKeyTransRecipient__SWIG_1(VirgilCMSKeyTransRecipient.getCPtr(other), other), true);
  }

}
