/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.virgilsecurity.crypto;

public class VirgilPFSEncryptedMessage implements java.lang.AutoCloseable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VirgilPFSEncryptedMessage(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VirgilPFSEncryptedMessage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        virgil_crypto_javaJNI.delete_VirgilPFSEncryptedMessage(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  public void close() {
    delete();
  }

  public VirgilPFSEncryptedMessage(byte[] sessionIdentifier, byte[] salt, byte[] cipherText) {
    this(virgil_crypto_javaJNI.new_VirgilPFSEncryptedMessage(sessionIdentifier, salt, cipherText), true);
  }

  public byte[] getSessionIdentifier() {
    return virgil_crypto_javaJNI.VirgilPFSEncryptedMessage_getSessionIdentifier(swigCPtr, this);
  }

  public byte[] getSalt() {
    return virgil_crypto_javaJNI.VirgilPFSEncryptedMessage_getSalt(swigCPtr, this);
  }

  public byte[] getCipherText() {
    return virgil_crypto_javaJNI.VirgilPFSEncryptedMessage_getCipherText(swigCPtr, this);
  }

}
