/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.virgilsecurity.crypto;

public class VirgilPFSInitiatorPrivateInfo implements java.lang.AutoCloseable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VirgilPFSInitiatorPrivateInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VirgilPFSInitiatorPrivateInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        virgil_crypto_javaJNI.delete_VirgilPFSInitiatorPrivateInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  public void close() {
    delete();
  }

  public VirgilPFSInitiatorPrivateInfo(VirgilPFSPrivateKey identityPrivateKey, VirgilPFSPrivateKey ephemeralPrivateKey) {
    this(virgil_crypto_javaJNI.new_VirgilPFSInitiatorPrivateInfo(VirgilPFSPrivateKey.getCPtr(identityPrivateKey), identityPrivateKey, VirgilPFSPrivateKey.getCPtr(ephemeralPrivateKey), ephemeralPrivateKey), true);
  }

  public VirgilPFSPrivateKey getIdentityPrivateKey() {
    return new VirgilPFSPrivateKey(virgil_crypto_javaJNI.VirgilPFSInitiatorPrivateInfo_getIdentityPrivateKey(swigCPtr, this), false);
  }

  public VirgilPFSPrivateKey getEphemeralPrivateKey() {
    return new VirgilPFSPrivateKey(virgil_crypto_javaJNI.VirgilPFSInitiatorPrivateInfo_getEphemeralPrivateKey(swigCPtr, this), false);
  }

}
