/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.virgilsecurity.crypto;

public class VirgilCMSEncryptedContent extends VirgilAsn1Compatible implements java.lang.AutoCloseable {
  private transient long swigCPtr;

  protected VirgilCMSEncryptedContent(long cPtr, boolean cMemoryOwn) {
    super(virgil_crypto_javaJNI.VirgilCMSEncryptedContent_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VirgilCMSEncryptedContent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        virgil_crypto_javaJNI.delete_VirgilCMSEncryptedContent(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  @Override
  public void close() {
    delete();
  }

  public void setContentEncryptionAlgorithm(byte[] value) {
    virgil_crypto_javaJNI.VirgilCMSEncryptedContent_contentEncryptionAlgorithm_set(swigCPtr, this, value);
  }

  public byte[] getContentEncryptionAlgorithm() {
    return virgil_crypto_javaJNI.VirgilCMSEncryptedContent_contentEncryptionAlgorithm_get(swigCPtr, this);
  }

  public void setEncryptedContent(byte[] value) {
    virgil_crypto_javaJNI.VirgilCMSEncryptedContent_encryptedContent_set(swigCPtr, this, value);
  }

  public byte[] getEncryptedContent() {
    return virgil_crypto_javaJNI.VirgilCMSEncryptedContent_encryptedContent_get(swigCPtr, this);
  }

  public VirgilCMSEncryptedContent() {
    this(virgil_crypto_javaJNI.new_VirgilCMSEncryptedContent__SWIG_0(), true);
  }

  public VirgilCMSEncryptedContent(VirgilCMSEncryptedContent other) {
    this(virgil_crypto_javaJNI.new_VirgilCMSEncryptedContent__SWIG_1(VirgilCMSEncryptedContent.getCPtr(other), other), true);
  }

}
