/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.virgilsecurity.crypto;

public class VirgilRandom implements java.lang.AutoCloseable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VirgilRandom(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VirgilRandom obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        virgil_crypto_javaJNI.delete_VirgilRandom(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  public void close() {
    delete();
  }

  public VirgilRandom(String personalInfo) {
    this(virgil_crypto_javaJNI.new_VirgilRandom__SWIG_0(personalInfo), true);
  }

  public byte[] randomize(long bytesNum) {
    return virgil_crypto_javaJNI.VirgilRandom_randomize__SWIG_0(swigCPtr, this, bytesNum);
  }

  public long randomize() {
    return virgil_crypto_javaJNI.VirgilRandom_randomize__SWIG_1(swigCPtr, this);
  }

  public long randomize(long min, long max) {
    return virgil_crypto_javaJNI.VirgilRandom_randomize__SWIG_2(swigCPtr, this, min, max);
  }

  public VirgilRandom(VirgilRandom rhs) {
    this(virgil_crypto_javaJNI.new_VirgilRandom__SWIG_1(VirgilRandom.getCPtr(rhs), rhs), true);
  }

}
