/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.virgilsecurity.crypto;

public class VirgilPFSPrivateKey implements java.lang.AutoCloseable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VirgilPFSPrivateKey(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VirgilPFSPrivateKey obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        virgil_crypto_javaJNI.delete_VirgilPFSPrivateKey(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  public void close() {
    delete();
  }

  public VirgilPFSPrivateKey(byte[] key, byte[] password) {
    this(virgil_crypto_javaJNI.new_VirgilPFSPrivateKey__SWIG_0(key, password), true);
  }

  public VirgilPFSPrivateKey(byte[] key) {
    this(virgil_crypto_javaJNI.new_VirgilPFSPrivateKey__SWIG_1(key), true);
  }

  public VirgilPFSPrivateKey() {
    this(virgil_crypto_javaJNI.new_VirgilPFSPrivateKey__SWIG_2(), true);
  }

  public boolean isEmpty() {
    return virgil_crypto_javaJNI.VirgilPFSPrivateKey_isEmpty(swigCPtr, this);
  }

  public byte[] getKey() {
    return virgil_crypto_javaJNI.VirgilPFSPrivateKey_getKey(swigCPtr, this);
  }

  public byte[] getPassword() {
    return virgil_crypto_javaJNI.VirgilPFSPrivateKey_getPassword(swigCPtr, this);
  }

  public VirgilPFSPrivateKey(VirgilPFSPrivateKey other) {
    this(virgil_crypto_javaJNI.new_VirgilPFSPrivateKey__SWIG_3(VirgilPFSPrivateKey.getCPtr(other), other), true);
  }

}
