/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.virgilsecurity.crypto;

public class VirgilPFSInitiatorPublicInfo implements java.lang.AutoCloseable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VirgilPFSInitiatorPublicInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VirgilPFSInitiatorPublicInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        virgil_crypto_javaJNI.delete_VirgilPFSInitiatorPublicInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  public void close() {
    delete();
  }

  public VirgilPFSInitiatorPublicInfo(VirgilPFSPublicKey identityPublicKey, VirgilPFSPublicKey ephemeralPublicKey) {
    this(virgil_crypto_javaJNI.new_VirgilPFSInitiatorPublicInfo(VirgilPFSPublicKey.getCPtr(identityPublicKey), identityPublicKey, VirgilPFSPublicKey.getCPtr(ephemeralPublicKey), ephemeralPublicKey), true);
  }

  public VirgilPFSPublicKey getIdentityPublicKey() {
    return new VirgilPFSPublicKey(virgil_crypto_javaJNI.VirgilPFSInitiatorPublicInfo_getIdentityPublicKey(swigCPtr, this), false);
  }

  public VirgilPFSPublicKey getEphemeralPublicKey() {
    return new VirgilPFSPublicKey(virgil_crypto_javaJNI.VirgilPFSInitiatorPublicInfo_getEphemeralPublicKey(swigCPtr, this), false);
  }

}
