/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.virgilsecurity.crypto;

public class VirgilCMSEnvelopedData extends VirgilAsn1Compatible implements java.lang.AutoCloseable {
  private transient long swigCPtr;

  protected VirgilCMSEnvelopedData(long cPtr, boolean cMemoryOwn) {
    super(virgil_crypto_javaJNI.VirgilCMSEnvelopedData_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VirgilCMSEnvelopedData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        virgil_crypto_javaJNI.delete_VirgilCMSEnvelopedData(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  @Override
  public void close() {
    delete();
  }

  public void setKeyTransRecipients(SWIGTYPE_p_std__vectorT_virgil__crypto__foundation__cms__VirgilCMSKeyTransRecipient_t value) {
    virgil_crypto_javaJNI.VirgilCMSEnvelopedData_keyTransRecipients_set(swigCPtr, this, SWIGTYPE_p_std__vectorT_virgil__crypto__foundation__cms__VirgilCMSKeyTransRecipient_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_virgil__crypto__foundation__cms__VirgilCMSKeyTransRecipient_t getKeyTransRecipients() {
    long cPtr = virgil_crypto_javaJNI.VirgilCMSEnvelopedData_keyTransRecipients_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_virgil__crypto__foundation__cms__VirgilCMSKeyTransRecipient_t(cPtr, false);
  }

  public void setPasswordRecipients(SWIGTYPE_p_std__vectorT_virgil__crypto__foundation__cms__VirgilCMSPasswordRecipient_t value) {
    virgil_crypto_javaJNI.VirgilCMSEnvelopedData_passwordRecipients_set(swigCPtr, this, SWIGTYPE_p_std__vectorT_virgil__crypto__foundation__cms__VirgilCMSPasswordRecipient_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_virgil__crypto__foundation__cms__VirgilCMSPasswordRecipient_t getPasswordRecipients() {
    long cPtr = virgil_crypto_javaJNI.VirgilCMSEnvelopedData_passwordRecipients_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_virgil__crypto__foundation__cms__VirgilCMSPasswordRecipient_t(cPtr, false);
  }

  public void setEncryptedContent(VirgilCMSEncryptedContent value) {
    virgil_crypto_javaJNI.VirgilCMSEnvelopedData_encryptedContent_set(swigCPtr, this, VirgilCMSEncryptedContent.getCPtr(value), value);
  }

  public VirgilCMSEncryptedContent getEncryptedContent() {
    long cPtr = virgil_crypto_javaJNI.VirgilCMSEnvelopedData_encryptedContent_get(swigCPtr, this);
    return (cPtr == 0) ? null : new VirgilCMSEncryptedContent(cPtr, false);
  }

  public VirgilCMSEnvelopedData() {
    this(virgil_crypto_javaJNI.new_VirgilCMSEnvelopedData__SWIG_0(), true);
  }

  public VirgilCMSEnvelopedData(VirgilCMSEnvelopedData other) {
    this(virgil_crypto_javaJNI.new_VirgilCMSEnvelopedData__SWIG_1(VirgilCMSEnvelopedData.getCPtr(other), other), true);
  }

}
