/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.virgilsecurity.crypto;

public class VirgilPFSResponderPrivateInfo implements java.lang.AutoCloseable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VirgilPFSResponderPrivateInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VirgilPFSResponderPrivateInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        virgil_crypto_javaJNI.delete_VirgilPFSResponderPrivateInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  public void close() {
    delete();
  }

  public VirgilPFSResponderPrivateInfo(VirgilPFSPrivateKey identityPrivateKey, VirgilPFSPrivateKey longTermPrivateKey, VirgilPFSPrivateKey oneTimePrivateKey) {
    this(virgil_crypto_javaJNI.new_VirgilPFSResponderPrivateInfo__SWIG_0(VirgilPFSPrivateKey.getCPtr(identityPrivateKey), identityPrivateKey, VirgilPFSPrivateKey.getCPtr(longTermPrivateKey), longTermPrivateKey, VirgilPFSPrivateKey.getCPtr(oneTimePrivateKey), oneTimePrivateKey), true);
  }

  public VirgilPFSResponderPrivateInfo(VirgilPFSPrivateKey identityPrivateKey, VirgilPFSPrivateKey longTermPrivateKey) {
    this(virgil_crypto_javaJNI.new_VirgilPFSResponderPrivateInfo__SWIG_1(VirgilPFSPrivateKey.getCPtr(identityPrivateKey), identityPrivateKey, VirgilPFSPrivateKey.getCPtr(longTermPrivateKey), longTermPrivateKey), true);
  }

  public VirgilPFSPrivateKey getIdentityPrivateKey() {
    return new VirgilPFSPrivateKey(virgil_crypto_javaJNI.VirgilPFSResponderPrivateInfo_getIdentityPrivateKey(swigCPtr, this), false);
  }

  public VirgilPFSPrivateKey getLongTermPrivateKey() {
    return new VirgilPFSPrivateKey(virgil_crypto_javaJNI.VirgilPFSResponderPrivateInfo_getLongTermPrivateKey(swigCPtr, this), false);
  }

  public VirgilPFSPrivateKey getOneTimePrivateKey() {
    return new VirgilPFSPrivateKey(virgil_crypto_javaJNI.VirgilPFSResponderPrivateInfo_getOneTimePrivateKey(swigCPtr, this), false);
  }

}
