/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.virgilsecurity.crypto;

public class VirgilPFSPublicKey implements java.lang.AutoCloseable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VirgilPFSPublicKey(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VirgilPFSPublicKey obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        virgil_crypto_javaJNI.delete_VirgilPFSPublicKey(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  public void close() {
    delete();
  }

  public VirgilPFSPublicKey(byte[] key) {
    this(virgil_crypto_javaJNI.new_VirgilPFSPublicKey__SWIG_0(key), true);
  }

  public VirgilPFSPublicKey() {
    this(virgil_crypto_javaJNI.new_VirgilPFSPublicKey__SWIG_1(), true);
  }

  public boolean isEmpty() {
    return virgil_crypto_javaJNI.VirgilPFSPublicKey_isEmpty(swigCPtr, this);
  }

  public byte[] getKey() {
    return virgil_crypto_javaJNI.VirgilPFSPublicKey_getKey(swigCPtr, this);
  }

}
